language: python
python:
  - "3.5"
# command to install dependencies
install: "pip install -r calcroyalties/requirements.txt"
# command to run tests
# script: py.test --cov=excel-app/ --cov-report=xml
script: py.test calcroyalties/ --cov=calcroyalties/ --cov-report=xml

notifications:
  email:
    recipients:
      - konstantin.lazutin@thesolutionstack.com
      - larry.shumlich@thesolutionstack.com

before_install:
  - pip install codecov

  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
after_success:
  - codecov
